# Generated by Django 4.1.3 on 2023-01-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_bought_products', models.JSONField(default=dict, editable=False)),
                ('web_theme', models.CharField(editable=False, max_length=30)),
                ('kvkk_agreed', models.BooleanField(editable=False)),
                ('email_permission', models.BooleanField(editable=False)),
                ('login_count', models.IntegerField(default=0, editable=False)),
                ('total_logged_time', models.DurationField(editable=False)),
                ('last_logged_in', models.DateTimeField(editable=False)),
                ('total_point', models.IntegerField(default=0, editable=False)),
                ('login_strike', models.IntegerField(default=0, editable=False)),
                ('profile_rank', models.CharField(choices=[('rookie', 'ROOKIE')], default='rookie', editable=False, max_length=10)),
                ('profile_user', models.CharField(editable=False, max_length=50)),
                ('profile_oses', models.JSONField(default=dict, editable=False)),
                ('profile_platforms', models.JSONField(default=dict, editable=False)),
                ('profile_browsers', models.JSONField(default=dict, editable=False)),
                ('is_bot', models.BooleanField(default=False, editable=False)),
                ('ip_addresses', models.JSONField(default=dict, editable=False)),
                ('account_verifications', models.JSONField(default=dict, editable=False)),
                ('user_restricted', models.BooleanField(default=False)),
                ('user_notifications', models.JSONField(blank=True, default=dict)),
                ('profile_followers', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('account', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
