# Generated by Django 4.1.3 on 2022-11-11 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 13, 24, 5, 878252)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_logged_time',
            field=models.DurationField(auto_created=True, default=datetime.timedelta(seconds=1)),
            preserve_default=False,
        ),
    ]
