# Generated by Django 4.0.3 on 2022-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_logged_time',
            field=models.CharField(default='Never', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
