# Generated by Django 4.0.3 on 2022-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_average_logged_time_profile_last_logged_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='average_logged_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateTimeField(),
        ),
    ]
