# Generated by Django 4.1.3 on 2022-11-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_last_logged_in_profile_login_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_logged_time',
            field=models.DurationField(),
        ),
    ]
