# Generated by Django 4.0.3 on 2022-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_profile_average_logged_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_logged_time',
            field=models.DurationField(default=False),
            preserve_default=False,
        ),
    ]
