# Generated by Django 4.0.3 on 2022-11-11 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_average_logged_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_logged_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_logged_time',
            field=models.DurationField(default=datetime.timedelta),
            preserve_default=False,
        ),
    ]
