# Generated by Django 4.0.3 on 2022-11-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_profile_total_logged_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_logged_time',
            field=models.DurationField(null=True),
        ),
    ]
