# Generated by Django 4.0.3 on 2022-11-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_profile_total_logged_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_logged_time',
        ),
    ]
