# Generated by Django 4.1.3 on 2022-12-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=100)),
                ('product_fee', models.IntegerField()),
                ('product_image', models.URLField()),
                ('product_sold_count', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_sources', models.TextField()),
                ('topic_keywords', models.CharField(max_length=40)),
                ('topic_video_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_genre', models.CharField(choices=[('bugfix', 'Bugfix'), ('design', 'Design'), ('development', 'Development'), ('cybersecurity', 'Cyber Security'), ('dbms', 'DBMS')], max_length=20)),
                ('update_work', models.CharField(max_length=75)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_authors', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_content', models.TextField()),
                ('idea_publish_date', models.DateTimeField(auto_now=True)),
                ('idea_likes', models.JSONField(default=dict)),
                ('idea_like_count', models.IntegerField(default=0, editable=False)),
                ('idea_comments', models.IntegerField(default=0, editable=False)),
                ('idea_topic', models.CharField(default='Belirlenemedi.', max_length=100, null=True)),
                ('idea_archived', models.BooleanField(default=False)),
                ('idea_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_publish_date', models.DateTimeField(auto_now=True)),
                ('comment_likes', models.JSONField(default=dict, editable=False)),
                ('comment_like_count', models.IntegerField(default=0, editable=False)),
                ('comment_dislikes', models.JSONField(default=dict, editable=False)),
                ('comment_dislike_count', models.IntegerField(default=0, editable=False)),
                ('comment_topic', models.CharField(default='Belirlenemedi.', max_length=100, null=True)),
                ('comment_archived', models.BooleanField(default=False)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
                ('comment_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.idea')),
            ],
        ),
    ]
