# Generated by Django 4.0.3 on 2022-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_comments',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
