# Generated by Django 4.1.3 on 2022-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_date',
            field=models.DateTimeField(),
        ),
    ]
