# Generated by Django 4.1.3 on 2022-12-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '__first__'),
        ('idea', '0002_alter_topic_topic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_rate',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_survey',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_fullname', models.CharField(max_length=40)),
                ('feedback_email', models.EmailField(max_length=254)),
                ('feedback_message', models.TextField()),
                ('feedback_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
