# Generated by Django 4.0.3 on 2022-11-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_comment_comment_dislike_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_idea',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='idea.idea'),
            preserve_default=False,
        ),
    ]
