# Generated by Django 4.0.3 on 2022-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_comment_comment_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_dislikes',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_likes',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
