# Generated by Django 4.0.3 on 2022-11-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_alter_comment_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea_comments',
        ),
    ]
