# Generated by Django 4.0.3 on 2022-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_remove_idea_idea_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_comments',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
