# Generated by Django 4.0.3 on 2022-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_idea_idea_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_sources', models.TextField()),
                ('topic_keywords', models.CharField(max_length=40)),
            ],
        ),
    ]
